// Reservations
export const GET_RESERVATIONS_DATA = 'GET_RESERVATIONS_DATA'
export const ERROR_RESERVATIONS = 'ERROR_RESERVATIONS'
export const SET_LOADING_RESERVATIONS = 'SET_LOADING_RESERVATIONS'
// Schedules
export const GET_SCHEDULES = 'GET_SCHEDULES'
export const LOAD_ROUTES = 'LOAD_ROUTES'
export const ERROR_SCHEDULES = 'ERROR_SCHEDULES'
export const SET_LOADING_SCHEDULES = 'SET_LOADING_SCHEDULES'
