// Reservations
export const GET_RESERVATIONS_DATA = 'GET_RESERVATIONS_DATA'
export const ERROR_RESERVATIONS = 'ERROR_RESERVATIONS'
export const SET_LOADING_RESERVATIONS = 'SET_LOADING_RESERVATIONS'
export const GET_RESERVATIONS_BY_ID = 'GET_RESERVATIONS_BY_ID'
// Schedules
export const GET_SCHEDULES = 'GET_SCHEDULES'
export const LOAD_ROUTES = 'LOAD_ROUTES'
export const ERROR_SCHEDULES = 'ERROR_SCHEDULES'
export const SET_LOADING_SCHEDULES = 'SET_LOADING_SCHEDULES'
// Users
export const GET_USER_BY_ID = 'GET_USER_BY_ID'
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const SET_LOADING_USERS = 'SET_LOADING_USERS'
export const ERROR_USERS = 'ERROR_USERS'
// Agents
export const GET_ALL_AGENTS = 'GET_ALL_AGENTS'
export const SET_LOADING_AGENTS = 'SET_LOADING_AGENTS'
export const ERORR_AGENTS = 'ERROR_AGENTS'
